[versions]
composePlugin = "1.9.1"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"

kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
kotlinxDatetime = "0.7.1"
kotlinxImmutable = "0.4.0"
kotlinxIo = "0.8.0"

ktor = "3.3.1"

navigation = "2.9.1"
lifecycle = "2.9.5"
material3 = "1.9.0"
material3Adaptive = "1.2.0-alpha05"
savedstate = "1.3.5"
windowCore = "1.4.0"

androidxAnnotation = "1.9.1"
androidxCollection = "1.5.0"
androidxPaging = "3.4.0-alpha04"
androidxDataStore = "1.1.7"

koin = "4.1.1"
koinAnnotations = "2.3.0"

coil = "3.3.0"

okio = "3.16.2"

haze = "1.6.10"

kermit = "2.0.8"

ktlintPlugin = "13.1.0"

# Android
agp = "8.10.1"
androidCompileSdk = "36"
androidMinSdk = "24"
androidTargetSdk = "36"
androidxActivityCompose = "1.10.1"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }

kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }

lifecycle-common = { module = "org.jetbrains.androidx.lifecycle:lifecycle-common", version.ref = "lifecycle" }
lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }

material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3Adaptive" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "material3Adaptive" }
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "material3Adaptive" }

savedstate = { module = "org.jetbrains.androidx.savedstate:savedstate", version.ref = "savedstate" }

window-core = { module = "org.jetbrains.androidx.window:window-core", version.ref = "windowCore" }

androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }

androidx-collection = { module = "androidx.collection:collection", version.ref = "androidxCollection" }

androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidxPaging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidxPaging" }
androidx-paging-test = { module = "androidx.paging:paging-testing", version.ref = "androidxPaging" }

androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidxDataStore" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-annotation = { module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotations" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotations" }

coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# Android
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }

# Test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlintPlugin = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }

# Android
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Custom
sharedModule = { id = "com.reach.kmp.shared", version = "unspecified" }

featureModule = { id = "com.reach.kmp.feature", version = "unspecified" }
featureDataModule = { id = "com.reach.kmp.feature.data", version = "unspecified" }
uiCoreModule = { id = "com.reach.kmp.ui.core", version = "unspecified" }
uiBaseModule = { id = "com.reach.kmp.ui.base", version = "unspecified" }
dataCoreModule = { id = "com.reach.kmp.data.core", version = "unspecified" }
dataBaseModule = { id = "com.reach.kmp.data.base", version = "unspecified" }
